FROM mcr.microsoft.com/dotnet/runtime:7.0 AS base
WORKDIR /app

FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build
WORKDIR /src
COPY ["src/Structural/Adapter/Adapter.csproj", "src/Structural/Adapter/"]
RUN dotnet restore "src/Structural/Adapter/Adapter.csproj"
COPY . .
WORKDIR "/src/src/Structural/Adapter"
RUN dotnet build "Adapter.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "Adapter.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Adapter.dll"]
